### ISSUE TITLE
 Error Call to undefined method OC\Server::getEventDispatcher() Could not boot metadata: Call to undefined method OC\Server::getEventDispatcher() 

### ISSUE THREAD

**Issue by Jannik44** [gino0631/nextcloud-metadata#107] opened 2023-12-25 12:38 UTC

**Comment by Jannik44** [comment] 2023-12-25 12:38
nextcloud 28, this error spams the logs

**Comment by gino0631** [comment] 2023-12-25 14:01
Duplicate of #106

**Closed by gino0631** 2023-12-25 14:01 UTC
