### ISSUE TITLE
Fail to initialize the main page when using this app

### ISSUE THREAD

**Issue by WinstonH** [gino0631/nextcloud-metadata#8] opened 2017-10-11 08:09 UTC
The File page simply keeps on loading.
Everything works fine when it's disabled.
Already tried to reinstall Nextcloud twice, same problem.

Some details you may need:
Nextcloud-12.0.3
LNMP environment
nginx-1.12
php-7.0

**Comment by gino0631** [comment] 2017-10-11 11:09
Do you see any errors in your browser's console (F12), any failed network requests or relevant errors in the Nextcloud log?

**Comment by WinstonH** [comment] 2017-10-11 11:25
There's only one error in my browser's console:

Uncaught TypeError: Cannot read property 'getFullPath' of null
    at child.render (tabview.js?v=96a3006db210614596943654bb76b7fb-0:18)
    at child.setFileInfo (merged-index.js?v=96a3006db210614596943654bb76b7fb-0:8380)
    at child.selectTab (merged-index.js?v=96a3006db210614596943654bb76b7fb-0:8827)
    at child.render (merged-index.js?v=96a3006db210614596943654bb76b7fb-0:8785)
    at child.setFileInfo (merged-index.js?v=96a3006db210614596943654bb76b7fb-0:8846)
    at FileList._updateDetailsView (merged-index.js?v=96a3006db210614596943654bb76b7fb-0:4506)
    at FileList.reload (merged-index.js?v=96a3006db210614596943654bb76b7fb-0:5624)
    at FileList.changeDirectory (merged-index.js?v=96a3006db210614596943654bb76b7fb-0:5477)
    at FileList._onUrlChanged (merged-index.js?v=96a3006db210614596943654bb76b7fb-0:4571)
    at HTMLDivElement.dispatch (core.js?v=96a3006db210614596943654bb76b7fb-0:3)

Nothing in Nextcloud log

**Comment by gino0631** [comment] 2017-10-11 12:03
OK, what browser are you using?

**Comment by WinstonH** [comment] 2017-10-11 12:54
Chrome

**Comment by gino0631** [comment] 2017-10-11 16:00
Good. I can't reproduce the problem, but let's suppose it is caused by the "Uncaught TypeError", so I'll try to adjust the script.

**Comment by gino0631** [comment] 2017-10-12 01:03
Would it be possible for you to download the updated [tabview.js](https://raw.githubusercontent.com/gino0631/nextcloud-metadata/master/js/tabview.js), put it in `nextcloud/apps/metadata/js/`, reload and check if that helps?

**Comment by WinstonH** [comment] 2017-10-12 04:02
Well, I've done as you instructed. It doesn't seem to help.
I also tried to use the One-Click Setup in the cPanel, and I'm afraid the error come up once again.
To be honest, I know little about how this app functions. Is there any other possible factor that could interfere this ?

**Comment by gino0631** [comment] 2017-10-12 10:13
OK, just to confirm - are you getting the same "Uncaught TypeError: Cannot read property 'getFullPath' of null" with the same stacktrace? With the updated script at least the error should be different, because now I do a check for null before calling getFullPath (though I couldn't reproduce the problem).

**Comment by WinstonH** [comment] 2017-10-12 12:19
The log is just like this after updating the script:

Uncaught TypeError: Cannot read property 'getFullPath' of null
    at child.render (tabview.js?v=96a3006db210614596943654bb76b7fb-0:18)
    at child.setFileInfo (merged-index.js?v=96a3006db210614596943654bb76b7fb-0:8380)
    at child.selectTab (merged-index.js?v=96a3006db210614596943654bb76b7fb-0:8827)
    at child.render (merged-index.js?v=96a3006db210614596943654bb76b7fb-0:8785)
    at child.setFileInfo (merged-index.js?v=96a3006db210614596943654bb76b7fb-0:8846)
    at FileList._updateDetailsView (merged-index.js?v=96a3006db210614596943654bb76b7fb-0:4506)
    at FileList.reload (merged-index.js?v=96a3006db210614596943654bb76b7fb-0:5624)
    at FileList.changeDirectory (merged-index.js?v=96a3006db210614596943654bb76b7fb-0:5477)
    at FileList._onUrlChanged (merged-index.js?v=96a3006db210614596943654bb76b7fb-0:4571)
    at HTMLDivElement.dispatch (core.js:3)

And I guess I find the reason why your Nextcloud functons perfectly while mine didn't.
When the language is set to English or French (and maybe some others), everything works perfectly.
However, when it's Russian, Japanese or Chinese, the error come up.

I didn't check all of the languages one by one, but apparently some of them are not compatible with your app. Hopefully you'll solve this. Many thanks for your work.  lol~

**Comment by gino0631** [comment] 2017-10-12 12:57
Probably because in case of Russian, Japanese or Chinese the Metadata tab is the first one (if you don't have other apps like Checksum for example), while with other languages it is somewhere in the middle?

Tried changing the display language in the Personal preferences, still no luck. Do you set it for your user, or globally?

**Comment by WinstonH** [comment] 2017-10-12 13:56
Personal preferences, set for myself.

**Comment by gino0631** [comment] 2017-10-12 22:36
Finally, I have managed to reproduce the problem by disabling all other apps, so that only Metadata is left in the sidebar, and changing the language as proposed.

The corrected script, however, works. If the same error persists even after replacing the file, that's probably because the browser is still using the old copy, so I'd suggest refreshing the cache (F12 and then F5).

I'm planning to release an updated version of the app within 5-10 days.

**Comment by WinstonH** [comment] 2017-10-13 02:43
YES! I clean up my browser's cache and it works.
Again, thank you for your time, patience and help !

**Comment by gino0631** [comment] 2017-10-13 12:41
Good to hear :) I'm closing this issue then, and the corrected script will be released with the next version.

**Closed by gino0631** 2017-10-13 12:41 UTC
