### ISSUE TITLE
caught error 500 due to this app

### ISSUE THREAD

**Issue by NewRedsquare** [gino0631/nextcloud-metadata#52] opened 2020-01-21 19:47 UTC
hello, here is the log of the error. 
After I disabled it with occ , everything worked !

```
Error   PHP     Undefined variable: server at /var/www/cloud/apps/metadata/lib/AppInfo/Application.php#31                                                 2020-01-21T19:33:12+00:00

  Error   index   Exception: Call to a member function getContentSecurityPolicyManager() on null at lib/private/AppFramework/Http/Dispatcher.php line 109   2020-01-21T19:33:12+00:00

                  0. lib/private/AppFramework/App.php line 126
                     OC\AppFramework\Http\Dispatcher->dispatch(OCA\Files\Controller\ViewController {}, "index")
                  1. lib/private/AppFramework/Routing/RouteActionHandler.php line 47
                     OC\AppFramework\App::main(
                       "OCA\\Files\\Controller\\ViewController",
                       "index",
                       OC\AppFramework\DependencyInjection\DIContainer {},
                       {_route:"files.view.index"}
                     )
                  2. <<closure>>
                     OC\AppFramework\Routing\RouteActionHandler->__invoke({_route:"files.view.index"})
                  3. lib/private/Route/Router.php line 297
                     call_user_func(OC\AppFramework\Routing\RouteActionHandler {}, {_route:"files.view.index"})
                  4. lib/base.php line 997
                     OC\Route\Router->match("\/apps\/files\/")
                  5. index.php line 42
                     OC::handleRequest(

                     )
```

**Comment by gino0631** [comment] 2020-01-21 20:40
A duplicate of #49, please update the app to 0.11.1.

**Closed by gino0631** 2020-01-21 20:40 UTC
Labels: duplicate

**Comment by bushman413** [comment] 2020-01-21 20:46
I've just run into the same issue causing a 500 error, same error as well.
Ubuntu 18.04.3, NC 17.0.1, Metadata 0.11.0.
Got it working again by disabling the app with occ, updating to 0.11.1 and re-enabling. So far, so good.

**Comment by gino0631** [comment] 2020-01-21 20:58
Quite unexpected this is still happening, as I removed 0.11.0 from the app store already 😕
