### ISSUE TITLE
Metadata app - PHP Errors

### ISSUE THREAD

**Issue by HeyWatchOutDude** [gino0631/nextcloud-metadata#74] opened 2021-02-26 11:36 UTC
Hi,

I have noticed two errors in the logging of my nextcloud instance.

Nextcloud version: 20.0.8
OS: Ubuntu 20.04.2 LTS
PHP version: 7.4
Metadata app version: 0.12.0 (up to date)

Errror#1:
`{"reqId":"ZqXxXq4WqQvCoAIRl1Vr","level":3,"time":"2021-02-25T21:49:41+00:00","remoteAddr":"192.168.10.58","user":"USERNAME","app":"PHP","method":"GET","url":"/apps/metadata/get?source=%2FBilder%2FiPhone%2F21-02-10+09-17-04+5811.jpg","message":{"Exception":"Error","Message":"array_merge(): Expected parameter 1 to be an array, null given at /var/www/nextcloud/apps/metadata/lib/Service/MetadataService.php#79","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/apps/metadata/lib/Service/MetadataService.php","line":79,"function":"array_merge"},{"file":"/var/www/nextcloud/apps/metadata/lib/Controller/MetadataController.php","line":24,"function":"getMetadata","class":"OCA\\Metadata\\Service\\MetadataService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"get","class":"OCA\\Metadata\\Controller\\MetadataController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36","version":"20.0.7.1","id":"6038da5378b63"}`

Error#2:
`
{"reqId":"ZqXxXq4WqQvCoAIRl1Vr","level":3,"time":"2021-02-25T21:49:41+00:00","remoteAddr":"192.168.10.58","user":"USERNAME","app":"PHP","method":"GET","url":"/apps/metadata/get?source=%2FBilder%2FiPhone%2F21-02-10+09-17-04+5811.jpg","message":{"Exception":"Error","Message":"Undefined index: IFD0 at /var/www/nextcloud/apps/metadata/lib/Service/MetadataService.php#79","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/metadata/lib/Service/MetadataService.php","line":79,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/apps/metadata/lib/Controller/MetadataController.php","line":24,"function":"getMetadata","class":"OCA\\Metadata\\Service\\MetadataService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"get","class":"OCA\\Metadata\\Controller\\MetadataController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36","version":"20.0.7.1","id":"6038da5378ba9"}
`

**Comment by gino0631** [comment] 2021-02-26 11:56
@HeyWatchOutDude Most probably a duplicate of #66 - do you have a possibility to test with the current master branch?

**Comment by HeyWatchOutDude** [comment] 2021-02-26 14:27
> @HeyWatchOutDude Most probably a duplicate of #66 - do you have a possibility to test with the current master branch?

What should I test?

**Comment by gino0631** [comment] 2021-02-26 14:58
@HeyWatchOutDude the latest code of the App from GitHub. If you are not comfortable with that, that's OK, I'm planning a new release within a few days.

**Comment by HeyWatchOutDude** [comment] 2021-02-26 15:05
I think I will wait for the release. :)

**Comment by gino0631** [comment] 2021-02-27 23:45
The release is done. If the errors are still present, please reopen.

**Closed by gino0631** 2021-02-27 23:45 UTC
