### ISSUE TITLE
GPS-Info not always shown

### ISSUE THREAD

**Issue by lukasb314** [gino0631/nextcloud-metadata#15] opened 2018-07-28 09:11 UTC
Hello,

i figured out that GPS information is not always shown, depending on which camera i was using.

Photos taken on my iPhone work perfectly. GPS coordinates are being shown. Location is also shown by Name (city name).

Photos taken on my Canon don't work. GPS coordinates / city names don't show up on Nextcloud, even though the GPS coordinates and city names are written in the photos' EXIF information (checked it offline with Picasa and an EXIF tool).

What is the cause for that? Can you fix it?

Thanks!

**Comment by gino0631** [comment] 2018-07-28 10:43
Would it be possible for you to attach a sample photo, as I need to reproduce the problem?

**Comment by lukasb314** [comment] 2018-07-28 11:04
Hi ghino, thanks für taking care.

Attached you can find two photos. I hope the github uploader does not remove the EXIF data. I'll check it after the upload.

iPhone photo:
![18-07-27 19-44-12 3782](https://user-images.githubusercontent.com/29770540/43355916-91bb3054-9266-11e8-81b8-79d618a85c90.jpg)

Canon photo:
![img_4890_e](https://user-images.githubusercontent.com/29770540/43355930-caf4d1ea-9266-11e8-9ca7-52999531cc1c.JPG)

**Comment by lukasb314** [comment] 2018-07-28 11:07
OK, EXIF information has not been modified by the github uploader. That's good.

**Comment by gino0631** [comment] 2018-07-28 13:15
This behaviour is probably caused by [this PHP bug](https://bugs.php.net/bug.php?id=73004).

**Comment by lukasb314** [comment] 2018-07-30 05:54
Yes, the guys in that link describe the exact same problem (iPhone-EXIF is working while Canon-EXIF is not).

They also say it's been fixed in PHP 7.2. I'm running PHP 7.0, so I can't verify.

**Comment by gino0631** [comment] 2018-07-30 11:12
It's probably too early for PHP 7.2, so I'll try to workaround by parsing GPS info directly.

**Comment by lukasb314** [comment] 2018-07-30 14:36
For me it's not an urgent issue - I can wait for PHP 7.2 :)

But thank you for taking care!

**Comment by gino0631** [comment] 2018-08-12 16:27
Should be fixed in the latest release.

**Closed by gino0631** 2018-08-12 16:27 UTC
Labels: bug
