### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by sunjam** [gino0631/nextcloud-metadata#75] opened 2021-02-26 22:28 UTC
Related to #73 php8 support has been introduced in v21.  7.x support will continue for the time being.  Thanks for the great app!

**Comment by gino0631** [comment] 2021-02-27 23:44
It's a duplicate of #72, and is implemented in the latest v0.13.0.

Thanks for the positive feedback, it encourages to continue the work.

**Closed by gino0631** 2021-02-27 23:44 UTC
